version: 1
update_configs:
  - package_manager: "javascript"
    target_branch: development
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
    automerged_updates:
      - match:
          dependency_type: "all"
    default_reviewers:
      - "tylors"
    default_assignees:
      - "tylors"
